diff-hl-margin.el

Using Emacs 24.4.1 (in Debian), I cloned this repo into my ~/.emacs.d and added the following to my init.el:
```elisp
(add-to-list 'load-path (locate-user-emacs-file "diff-hl"))
(require 'diff-hl)
(global-diff-hl-mode)
(unless (window-system)
(require 'diff-hl-margin)
(diff-hl-margin-mode))
```
This caused the below error when starting Emacs
> Warning (initialization): An error occurred while loading `/home/mccoyj1/.emacs.d/init.el':
>
> Symbol's value as variable is void: diff-hl-margin-mode
Moving the use of `diff-hl-margin-mode` after its definition fixes the problem for me.

Move diff-hl-margin-side after diff-hl-margin-mode definition

---

diff-hl-margin.el
diff-hl.el

Declaring `diff-hl-margin-side` silences the byte-compiler, but you might also want to check whether you have to define the options more carefully (possibly using `:set-after`).
Also you might wanna change the newline encoding in `diff-hl.el`.

silence byte-compiler

---

diff-hl.el

Keymaps are usually defined using `defvar` which has the advantage that
it only sets a variables value if that is not defined yet.  As a result
re-evaluating (i.e. during development) a buffer that contains such a
definition does not reset the value, which would lose all user
customization.
Unfortunately `define-prefix-command` does not do that.  So use `defvar`
to define the variable and then also store the in the function cell
using `fset`.

Define diff-hl-command-map without destroying existing bindings

---

README.md
diff-hl-flydiff.el
diff-hl.el

See #33 
This isn't quite ready. It doesn't have the following advice for the two `vc` functions.
```emacs
(with-eval-after-load 'vc
(defun nadvice/vc-working-revision (file &optional backend concrete)
(if concrete
(vc-call-backend backend 'working-revision file t)
(or (vc-file-getprop file 'vc-working-revision)
(progn
(setq backend (or backend (vc-responsible-backend file)))
(when backend
(vc-file-setprop file 'vc-working-revision
(vc-call-backend backend 'working-revision file)))))))
(advice-add #'vc-working-revision :override #'nadvice/vc-working-revision))
(with-eval-after-load 'vc-git
(defun nadvice/vc-git-working-revision (old-fun file &optional concrete)
"Git-specific version of `vc-working-revision'."
(if concrete
(vc-git--rev-parse (funcall old-fun file))
(funcall old-fun file))) …
```

[WIP] Allow diffing on-the-fly

---

diff-hl.el

The ‘yes-or-no-p’ procedure doesn’t pad its prompt argument with a
space so before this commit the prompt becomes:
Revert current hunk in <file>?(yes or no)
After this commit the prompt gets fixed to:
Revert current hunk in <file>? (yes or no)

Fix revert prompt

---

diff-hl.el

In these situations, it's not a bug with the code, and opening the emacs
debugger is not useful. By using `user-error`, the debugger is not
activated but we still terminate with an informative message.

Use `user-error` when we can't proceed

---

diff-hl-flydiff.el
diff-hl.el

If the buffer is associated with a file that is moved to a different
directory, but outside of Emacs, we previously crashed:
Debugger entered--Lisp error: (file-error "Setting current directory" "No such file or directory" "/Users/whughes/redacted/")
call-process("git" nil (t nil) nil "diff-index" "-p" "--raw" "-z" "HEAD" "--" "docker-compose.yml")
apply(call-process "git" nil (t nil) nil ("diff-index" "-p" "--raw" "-z" "HEAD" "--" "docker-compose.yml"))
process-file("git" nil (t nil) nil "diff-index" "-p" "--raw" "-z" "HEAD" "--" "docker-compose.yml")
apply(process-file "git" nil (t nil) nil "diff-index" ("-p" "--raw" "-z" "HEAD" "--" "docker-compose.yml"))
vc-git--call((t nil) "diff-index" "-p" "--raw" "-z" "HEAD" "--" "docker-compose.yml")
apply(vc-git--call (t nil) "diff-index" ("-p" …

Don't attempt to highlight in a file that doesn't exist

---

diff-hl-amend.el

Emacs 28's byte-compiler was complaining about it not
being a member of any group.

Add global-diff-hl-amend-mode to diff-hl custom group

---

README.md
diff-hl-amend.el
diff-hl.el

Solves #134.
Usage: 
- `M-x vc-print-log`, then run `diff-hl-log-view-set-reference-rev-for-fileset` on a rev to set it as the reference for the fie. Run `diff-hl-reset-reference-rev-for-fileset` to reset.
- `M-x vc-print-root-log`, then run `diff-hl-log-view-set-reference-rev-for-repo` on a rev to set it as the reference for all files in the repo. Run `diff-hl-reset-reference-rev-for-repo` to reset.
I'll write the usage in README after we are done with the code.
Problems:
- I am not familiar with the `fileset` concept of `vc`. To me it's like always being the current file. If this is right, I'll change the command name and docstring to make more sense for the users.
- For some reason, after setting the reference rev, I have to disable and enable `diff-hl-mode` in the file buffers for it …

Set reference rev in change log buffer

---

diff-hl.el

When `diff-hl.el` is being loaded, and this defcustom is being defined, it is possible the setter will encounter a variable `global-diff-hl-mode` that is both bound and true, maybe due to a customs file with a `(custom-set-variable '(global-diff-hl-mode t))` in it being loaded before `diff-hl.el`. Therefore, during this defcustom definition, the default initializer will call the setting, which will attempt to call an autoloaded function `global-diff-hl-mode`, which will trigger another load of `diff-hl.el`, ad infinitum.
This PR uses the suggested fix in the [elisp manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Variable-Definitions.html) to only call the setter during customization.

Prevent diff-hl-side from triggering infloop

---

diff-hl-inline-popup.el
diff-hl-show-hunk.el

This minor change fixes the last line of the inline popup in terminal. The last content line had an extra underlined character at the end.
Also, `diff-hl-show-hunk--goto-hunk-overlay` is now more tolerant to previous errors.

Last line of inline-popup properly underlined in terminal.

---

Makefile

- Compile all libraries, including the main one.
- Make the "all" make target depend on "compile".
- Add the current directory to the load-path,
so that compiling doesn't fail completely.

Fix building libraries using make

---

diff-hl-show-hunk.el

Currently, after quitting the show-hunk overlay/posframe, the show hunk buffers are at the top of the buffer list, which breaks the usual expectation when switching buffers. Ancillary buffers should not ever be at the top of the buffer list after quitting their modes.

bury show hunk buffers on quit

---

README.md

Some people disable VC because it fixes various oddities in Emacs and the same features are provided by other packages such as Magit. In this case, diff-hl will silently do nothing, which is confusing. This PR adds a note to the README clarifying the requirements for using diff-hl.

Mention that VC must be enabled

---

.dir-locals.el

I noticed there was a need to untabify in the latest PR, hence should we settle on the code style rules? 
The suggested settings are similar to the ones used by Company, so hopefully, they may work well for diff-hl too.

Add .dir-locals.el

---

README.md
diff-hl.el

To inhibit diff-hl in remote buffers. This option is useful with slow
tramp connections.

Add new option diff-hl-disable-on-remote

---

diff-hl.el

otherwise, full hunks would get highlighted from a one-line change

fix diff switches for fossil

---

diff-hl-flydiff.el

It seems that `file-exists-p` can cause Tramp to attempt to reopen a broken connection.  This caused me a problem when I was editing a file via Tramp while `diff-hl-flydiff-mode` was enabled, and the host the file was on became unreachable.  Because the call to `file-remote-p` only occurs _after_ the call to `file-exists-p`, it caused Emacs to become unusable due to messages from Tramp about attempting to reconnect appearing continuously.  This patch fixes this behaviour by switching the order of the last two tests in the `or` form.

Prevent Tramp and `diff-hl-flydiff-mode` from making Emacs unusable if the remote host disappears

---

diff-hl.el
test/diff-hl-test.el

Problem: On a slow VC backend, `diff-hl-mode` freezes Emacs because `(diff-hl-changes)` takes a long time.
Changes:
- Add a custom variable `diff-hl-update-with-thread`.
- When set to true, update with a separate thread.

Allow updating indicators asynchronously (without blocking Emacs)

---

diff-hl.el

It is not always in a thread, hence, removing.

minor fix for diff-hl-update documentation

---

diff-hl.el

Hi,
Currently, the width of the bitmap indicators is the minimum of the fringe width or 16. 
This makes it a bit inflexible to configure the indicator width. For example, I can't configure the diff-hl indicator width to 1 when the fringe width is 8.
So, in this PR, I made the default width 16 customizable, so that the diff-hl indicator width can be flexibly configured.
Can you consider merging it?
Thanks.

Make the maximum width of the fringe indicators customizable

---

diff-hl.el

Note that for those specific switches, they are added on top of the original ones as `vc-jj` already sets `vc-jj-diff-switches` to non-nil (the value is `("--git")` by default to be specific).

Provide diff switches for jj

---

Makefile
diff-hl-flydiff.el
diff-hl-margin.el
diff-hl.el
test/diff-hl-adjust-test.el
test/diff-hl-test.el

This splits highlighting into two groups: diff between the buffer contents and HEAD (or staging area (*)), and diff between the latter and `diff-hl-reference-revision` (if set). Looks like this:
The new indicators use a specific bitmap and new faces, both of which can be customized. The default bitmap is an empty one, so on the screenshot it's the lines without the "border".
A new fn option is added as well: `diff-hl-highlight-reference-function`. For more advanced customization.
(*) This change also uses the new indicators for the staged changes (Git only, naturally) when `diff-hl-show-staged-changes` is customized to nil. In a way that conflates those pieces of data, but I expect that most users will either use one or the other, and the behavior still makes sense when combined.

Reference revision diff highlights

---

diff-hl.el
test/diff-hl-test.el

**Problem**:
`diff-hl-resolved-reference-revision` fails to work correctly when `diff-hl-reference-revision` is set as a buffer-local variable.
Example:
```emacs-lisp
(setq-local diff-hl-reference-revision "test-rev")
```
**Cause**:
When the implementation for backends like Hg (and similarly Bzr) uses `with-temp-buffer`, buffer-local variables from the original buffer context are not accessible. Consequently, `diff-hl-reference-revision` evaluates to `nil` within the temporary buffer.
For 'Hg as an exmaple,
```emacs-lisp
(with-temp-buffer
(vc-hg-command (current-buffer) 0 nil
"identify" "-r" diff-hl-reference-revision
"-i")
...)
```
This leads to an incorrect command being executed:
*   **Expected hg command**: `hg identify -r test-rev -i`
*   **Actual hg command**: `hg identify -r -i` …

Fix `diff-hl-resolved-reference-revision` for Hg and Bzr with buffer-local `diff-hl-reference-revision`
